[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: wss: data: blob:"
